name: Docker Maven Test with Allure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t maven-allure-tests .

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            maven-allure-tests

      - name: List Allure Results
        run: ls -la allure-results  # Confirme que o diretório existe e contém arquivos

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip
          sudo unzip allure-2.30.0.zip -d /opt
          sudo ln -s /opt/allure-2.30.0/bin/allure /usr/local/bin/allure
          allure --version

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report  # Usando allure-results diretamente

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: allure-report
