name: Docker Maven Test with Allure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Passo 3: Fazer cache das camadas Docker
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Passo 4: Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t maven-allure-tests .

      # Passo 5: Executar os testes dentro do container Docker
      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            maven-allure-tests

      # Passo 6: Ajustar permissões (caso necessário)
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}

      # Passo 7: Instalar o Allure no runner do GitHub Actions (não no Docker)
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip
          sudo unzip allure-2.30.0.zip -d /opt
          sudo ln -s /opt/allure-2.30.0/bin/allure /usr/local/bin/allure
          allure --version

      # Passo 8: Gerar o relatório do Allure
      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o allure-report

      # Passo 9: Fazer upload do relatório do Allure como um artefato
      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      # Passo 10: Publicar o relatório no GitHub Pages (opcional)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
